name: food_safety
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter_intl:
  main_locale: en
  enabled: true

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  either_dart: ^1.0.0
  equatable: ^2.0.5
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.2.1
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_loggy: 2.0.3+1
  flutter_loggy_dio: ^3.1.0
  flutter_svg: ^2.0.9
  flutter_widget_from_html: ^0.15.0
  font_awesome_flutter: ^10.7.0
  form_builder_validators: ^11.0.0
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.10
  intl: ^0.19.0
  json_annotation: ^4.8.1
  loggy: ^2.0.3
  mobile_scanner: 5.2.3
  openfoodfacts: ^3.18.1
  permission_handler: ^11.3.1
  q_architecture: ^1.0.1
  retrofit: ^4.1.0
  sentry_flutter: ^8.10.1
  webview_flutter: ^4.7.0
  gap: ^3.0.1
  keyboard_actions: ^4.2.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  google_sign_in: ^6.2.2
  firebase_storage: ^12.3.6
  another_flushbar: ^1.12.30
  persistent_bottom_nav_bar_v2: ^5.3.1
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  build_runner: ^2.4.8
  dart_code_metrics: ^5.7.6
  flutter_flavorizr: ^2.2.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  retrofit_generator: ^8.1.0
  state_notifier_test: ^0.0.10

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flavorizr:
  app:
    android:
      flavorDimensions: "app"

  flavors:
    dev:
      app:
        name: "Food Safety Dev"
      android:
        applicationId: "com.foodsafety.dev"

      ios:
        bundleId: "com.foodsafety.dev"

    staging:
      app:
        name: "Food Safety Staging"
      android:
        applicationId: "com.foodsafety.staging"

      ios:
        bundleId: "com.foodsafety.staging"

    prod:
      app:
        name: "Food Safety"
      android:
        applicationId: "com.foodsafety"

      ios:
        bundleId: "com.foodsafety"
